<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="RhinoCommon" Version="8.34.26223.11001" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageVersion Include="RhinoFoundry.UI" Version="0.3.0-preview.1" />
    <PackageVersion Include="RhinoFoundry.UI.Primitives" Version="0.3.0-preview.1" />
    <PackageVersion Include="RhinoFoundry.UI.MacOS" Version="0.3.0-preview.1" />
  </ItemGroup>
</Project>
