<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RhinoLayoutFoundry.UI</RootNamespace>
    <AssemblyName>RhinoLayoutFoundry.UI</AssemblyName>
    <RhinoMacResources Condition="'$(RhinoMacResources)' == ''">/Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Versions/A/Resources</RhinoMacResources>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RhinoLayoutFoundry.Core\RhinoLayoutFoundry.Core.csproj" />
    <ProjectReference Include="..\RhinoLayoutFoundry.Extensibility\RhinoLayoutFoundry.Extensibility.csproj" />
    <PackageReference Include="RhinoFoundry.UI" />
    <PackageReference Include="RhinoCommon" ExcludeAssets="runtime" />
  </ItemGroup>
  <PropertyGroup Condition="'$(FoundryPlatform)' == 'MacOS'">
    <DefineConstants>$(DefineConstants);FOUNDRY_SHARED_MACOS</DefineConstants>
  </PropertyGroup>
  <ItemGroup Condition="'$(FoundryPlatform)' == 'MacOS'">
    <PackageReference Include="RhinoFoundry.UI.MacOS" />
  </ItemGroup>
</Project>
